"""
    Madaster Private API - Build: 

    Welcome to the **Madaster Private API** endpoint. This endpoint can be used to interact with the Madaster Platform and its resources. This API does not fully cover all functionality of the platform yet, please see below for the available functions and what they can be used for. For detailed information about the platform and this API, please refer to the [Madaster Documentation](https://docs.madaster.com) or the [Madaster API Documentation](https://docs.madaster.com/api).<br/><br/>To access these resources, you need an authorization token. If you do not have one yet, see the chapter about Authorization in the [API documentation](https://docs.madaster.com/api). This token should be sent as a header with the name 'X-API-Key', which will authenticate the request with the token. The documentation below specifies which requests are available and which responses they might produce.<br/><br/>This API can be reached at the endpoint: **[https://api.madaster.com/](https://api.madaster.com/)**<br/>The interactive Swagger/OpenAPI documentation can be found at: **[https://api.madaster.com/](https://api.madaster.com/)**<br/>If you prefer a static documentation: **[https://docs.madaster.com/api-docs](https://docs.madaster.com/api-docs)**  # noqa: E501

    The version of the OpenAPI document: v3.0
    Contact: service@madaster.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from madasterapi.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from madasterapi.model.multi_lingual_string import MultiLingualString
    from madasterapi.model.product_circular_information import ProductCircularInformation
    from madasterapi.model.product_dimension import ProductDimension
    from madasterapi.model.product_type import ProductType
    globals()['MultiLingualString'] = MultiLingualString
    globals()['ProductCircularInformation'] = ProductCircularInformation
    globals()['ProductDimension'] = ProductDimension
    globals()['ProductType'] = ProductType


class ProductRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('technical_lifetime',): {
            'inclusive_maximum': 1000,
            'inclusive_minimum': 0,
        },
        ('functional_lifetime',): {
            'inclusive_maximum': 1000,
            'inclusive_minimum': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name': (MultiLingualString,),  # noqa: E501
            'product_type': (ProductType,),  # noqa: E501
            'circular': (ProductCircularInformation,),  # noqa: E501
            'description': (MultiLingualString,),  # noqa: E501
            'supplier': (str, none_type,),  # noqa: E501
            'product_code': (str, none_type,),  # noqa: E501
            'technical_lifetime': (int,),  # noqa: E501
            'functional_lifetime': (int,),  # noqa: E501
            'fixed_dimensions': ([ProductDimension], none_type,),  # noqa: E501
            'default_dimensions': ([ProductDimension], none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name': 'name',  # noqa: E501
        'product_type': 'productType',  # noqa: E501
        'circular': 'circular',  # noqa: E501
        'description': 'description',  # noqa: E501
        'supplier': 'supplier',  # noqa: E501
        'product_code': 'productCode',  # noqa: E501
        'technical_lifetime': 'technicalLifetime',  # noqa: E501
        'functional_lifetime': 'functionalLifetime',  # noqa: E501
        'fixed_dimensions': 'fixedDimensions',  # noqa: E501
        'default_dimensions': 'defaultDimensions',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, name, product_type, circular, *args, **kwargs):  # noqa: E501
        """ProductRequest - a model defined in OpenAPI

        Args:
            name (MultiLingualString):
            product_type (ProductType):
            circular (ProductCircularInformation):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            description (MultiLingualString): [optional]  # noqa: E501
            supplier (str, none_type): The supplier of the product. [optional]  # noqa: E501
            product_code (str, none_type): The product code (EAN). [optional]  # noqa: E501
            technical_lifetime (int): The technical lifetime of the product, in years. [optional]  # noqa: E501
            functional_lifetime (int): The functional lifetime of the product, in years. [optional]  # noqa: E501
            fixed_dimensions ([ProductDimension], none_type): Gets or sets the dimensions.. [optional]  # noqa: E501
            default_dimensions ([ProductDimension], none_type): Gets or sets the dimensions.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.name = name
        self.product_type = product_type
        self.circular = circular
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
